name: Testing new Repo.

on:
  push:
    branches:
      - main
      - release/*

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Define Workflow Variable
        id: set_var
        run: |
          echo "Setting Workflow Variable"
          echo "name=Max" >> "$GITHUB_OUTPUT"
      - name: Use Workflow Variable
        run: |
          echo "Workflow Variable Value: ${{ steps.set_var.outputs.name }}"
      - name: Get host name
        run: |
          echo $hostname
